### PR TITLE
Vbd read access field from config

### PR DESCRIPTION
**Pull request by xakep-amatop**

### CODE REVIEW

**Comment by xakep-amatop** [comment]
@lorc @arminn @firscity ping

**Review by arminn — APPROVED** [review]

**Comment by arminn** [comment]
Reviewed-by: Andrii Chepurnyi andrii_chepurnyi@epam.com

**Comment by xakep-amatop** [comment]
added tag to commit messages

**Review by firscity — APPROVED** [review]
`Acked-by: Dmytro Firsov <dmytro_firsov@epam.com>`

**Comment by lorc** [comment]
I am okay with the changes, but...

> xen-dom-mgmt: minor fixes for vbd and vif

Can we please use imperative mood and descriptive headers?

**Comment by xakep-amatop** [comment]
> I am okay with the changes, but...
> 
> > xen-dom-mgmt: minor fixes for vbd and vif
> 
> Can we please use imperative mood and descriptive headers?

changed

**Comment by xakep-amatop** [comment]
> Reviewed-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com>

done

**Pull request merged**
