### PR TITLE
Cosmetic changes to xen-dom-mgmt related to old naming

### PR DESCRIPTION
**Pull request by firscity**

### CODE REVIEW

**Comment by LKomaryanskiy** [comment]
`Reviewed-by: Leonid Komarianskyi <leonid_komarianskyi@epam.com>`

**Review by LKomaryanskiy — APPROVED** [review]

**Comment by LKomaryanskiy** [comment]
@firscity do we have now to merge changes to main branch instead of wip_zephyr_dom0?

**Comment by firscity** [comment]
@LKomaryanskiy, yes, I tried to change your base to main from githhub in #33, but it failed.

**Comment by LKomaryanskiy** [comment]
@firscity Ok, thank you for the info. I'll manage this.

**Comment by firscity** [comment]
Added Leonid RB and changed commit messages to imperative mood.

**Comment by lorc** [comment]
Okay, if you want additional approval, then there it is:

`Acked-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com>`

**Comment by firscity** [comment]
@LKomaryanskiy and @lorc, thanks for review and approval, merged.

**Pull request merged**
