### PR TITLE
xrun: Move the xrun library to a separate project

### PR DESCRIPTION
**Pull request by Deedone**
From now on XRun will be in a separate project called zephyr-xrun.

### CODE REVIEW

**Comment by Deedone** [comment]
Related: https://github.com/xen-troops/zephyr-xrun/pull/1

**Comment by GrygiriiS** [comment]
This will kill RPI5 and zephyr-dom0-xt :(

**Comment by Deedone** [comment]
> This will kill RPI5 and zephyr-dom0-xt :(

Why do you think that?

**Comment by GrygiriiS** [comment]
Because it uses xrun/storage.

**Comment by GrygiriiS** [comment]
In my, personal, opinion this and also https://github.com/xen-troops/zephyr-xrun/pull/1 could be moved forward only when integration with AOS (or some other) project is done and proved to work.

**Comment by firscity** [comment]
I believe this change should have a better description with some prerequisites, because currently I am completely out of context and have no idea why it happening :)

**Comment by GrygiriiS** [comment]
I'd like to note that I'm not against it. And I'd like to clarify my above comment - such kind of changes have to be verified by integration, which means 

- or by providing additional PRs to dependent projects to switch to new SW structure
- or by providing SW migration notes for example in PR description or commit messages

Dependent projects AOS, RPI5 dom0

**Comment by GrygiriiS** [comment]
Thank you very very much.  i  see https://github.com/xen-troops/zephyr-dom0-xt/pull/22.

**Comment by firscity** [comment]
Please, also update this PR after all xrun related changes will be merged

**Review by firscity — APPROVED** [review]
`Acked-by: Dmytro Firsov <dmytro_firsov@epam.com>`

**Pull request merged**
